### ISSUE TITLE
Puppet approved

### ISSUE THREAD

**Issue by tphoney** [voxpupuli/puppet-windows-env#20]
@badgerious ,

I am reaching out to you on behalf of Puppet in regards to your Puppet Approved module puppet-windows-env on the Puppet Forge. The Puppet Approved criteria is based on the following tenets; quality composition, reliable operation, and active development. Your module has not been updated on the Puppet Forge for over a year, are there any plans to release a new version of the module? 

There seems to be a few open pull requests that could be merged. If there has not been a new release of the module on the Puppet Forge or a response in the following 3 months, we may have to revoke your Puppet Approved status. If you are not interested in continuing maintenance of the module, you may consider contacting the open source Puppet community Vox Pupuli. They are always interested in adopting modules. There is more information here https://voxpupuli.org/docs/#migrating-a-module-to-voxpupuli.

I look forward to your response, or a new release on the Puppet Forge. 

Regards,
TP Honey
Senior Software Engineer
Puppet Modules Team

**Comment by badgerious** [comment]
Hi @tphoney,

I no longer work professionally with puppet or Windows, and I've been allocating less and less time to this module such that it no longer makes progress with just me handling it. I've taken your advice and handed it off to voxpupuli so it may live on.

Cheers,
Eric

**Comment by bastelfreak** [comment]
Hai @tphoney,

we will kick out a new release in the next days.

**Comment by tphoney** [comment]
Thanks for the all the work you have put into this module @badgerious !! Your module is great and you should be very proud !
@bastelfreak thanks for the superb work, as always. 
I have created the ticket https://tickets.puppetlabs.com/browse/MODULES-4209 to move the approved banner to the new namespace. Just let me know when it is released, and i will get started on my side.

**Comment by tphoney** [comment]
The approval has now been moved. https://forge.puppet.com/puppet/windows_env
